<h2>Agregar</h2>
<div class="row">
    <div class="col-sm-6">
        <form action="<?php echo APP_URL."categorias/agregar"; ?>" method="POST">
            <p>
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" class="form-control">
            </p>
            <p>
                <input class="btn-primary" type="submit" value="Guardar categoria">
            </p>
        </form>
    </div>
    <div class="col-sm-6"></div>
</div>
