<h1>Editar categorías</h1>

<form action="<?php echo APP_URL."categorias/editar"; ?>" method="POST">
    <input type="hidden" name="id" value="<?php echo $this->categoria["id"]; ?>">
    <p>
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" value="<?php echo $this->categoria["nombre"]; ?>">
    </p>
    <p>
        <input type="submit" value="Guardar categoría">
    </p>
</form>